### ISSUE TITLE
Support AsyncAPI encoded in JSON

### ISSUE THREAD

**Issue by philCryoport** [asyncapi/vs-asyncapi-preview#123]
#### Reason/Context
Please try answering few of those questions
- Why we need this improvement?
It appears the current version of this extension only interprets YAML files.  AsyncAPI can also be encoded in JSON format.

- How will this change help?
We will be able to use this extension to view AsyncAPIs whether encoded in YAML or JSON

- What is the motivation? 
To offer full support for the AsyncAPI standard

#### Description
Please try answering few of those questions
- What changes have to be introduced?
At minimum, look for JSON files with the proper header -- and then offer to the user to use the preview

- Will this be a breaking change?
I hope not

- How could it be implemented/designed?
Haven't a clue.  I've never implemented a VSCode extension.

Thank you for your help!

**Comment by derberg** [comment]
@philCryoport Hey, thanks for reporting the issue.

Can you specify what version of the plugin you are using? I tried `asyncapi-preview v0.3.8` and JSON works like a charm

**Comment by philCryoport** [comment]
> @philCryoport Hey, thanks for reporting the issue.
> 
> Can you specify what version of the plugin you are using? I tried `asyncapi-preview v0.3.8` and JSON works like a charm

Hi there @derberg 

I'm using the same `asyncapi-preview` `0.3.8`.  

Here's my Visual Studio Code setup:
```
Version: 1.71.2
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:05:37.721Z (1 wk ago)
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 21.6.0
Sandboxed: No
```

I'm running MacOS Monterey 12.6.  No updates currently waiting for MacOS or for Visual Studio Code.

Guessing here:
* The "Activation Events" listed for the plugin need to include JSON as well? Here's what they are when viewing the extension in Visual Studio Code:
```
* onLanguage:yml
* onLanguage:yaml
* onCommand:asyncapi.preview
```

Then I finally figured out how to try to open a JSON file in the extension using the command palette:

1. It asks me to select a file
2. I select the JSON file
3. An error dialog box comes up: `Command 'Preview AsyncAPI' resulted in an error (The "path" argument must be of type string. Received undefined)`

Help?

**Comment by ivangsa** [comment]
Hi Phil

Thanks a lot for pin-pointing this issue and the solution..

We will release a fix shortly

In the meanwhile as you probably guessed you can get the extension
activated by opening any yml file..

Thanks for reporting this an sorry for the delay
Ivan

**Comment by philCryoport** [comment]
Hi @ivangsa I updated to 0.3.9 and reloaded Visual Studio Code.

Same error still: `Command 'Preview AsyncAPI' resulted in an error (The "path" argument must be of type string. Received undefined)`

**Comment by philCryoport** [comment]
It works! It works!  Thank you.

**Comment by philCryoport** [comment]
@asyncapi-bot  this can be closed
