### ISSUE TITLE
Some channel names generate errors in VS Extension but work in AsyncAPI Studio

### ISSUE THREAD

**Issue by Sergey-Terekhin** [asyncapi/vs-asyncapi-preview#166]
#### Describe the bug
Hello! I've created some async api document with real channel names we use in out project in the online AsyncAPI Studio (https://studio.asyncapi.com). It works perfectly, but then I load the same document into VS Code with the extension installed, I receive the following errors and preview is not shown:
```
6.TestChannel?Content-Type=application/json;charset=utf-8 channel contains invalid name with url query parameters: ?Content-Type=application/json;charset=utf-8
```

I understand that channel name looks weird, but we can not change it at least fast...

The same document is shown correctly in AsyncAPI Studio:
![изображение](https://user-images.githubusercontent.com/5369802/228513692-84ecdeb8-ac06-4019-bc74-c3df209f9302.png)

#### How to Reproduce
Sample async api document to reproduce the issue:
```yaml
asyncapi: 2.6.0
info:
  title: Test Service
  version: 1.0.0
channels:
  TestChannel?Content-Type=application/json;charset=utf-8:
    publish:
      message:
        $ref: '#/components/messages/TestMessage'
components:
  messages:
    TestMessage:
      contentType: application/json
      description: test message model
```

#### Expected behavior
Preview is shown as in the official online tool

**Comment by ivangsa** [comment]
Hi @Sergey-Terekhin 

It seems there is a bug in Studio, which uses next parser-js version 2.x which does not properly validate channel names

> https://www.asyncapi.com/docs/reference/specification/v2.6.0#channelsObject  says that query params are not allowed in channel name, SHALL NOT is like MUST NOT

This has been reported in upstream library https://github.com/asyncapi/parser-js/issues/740

Thanks for your report..

**Comment by Sergey-Terekhin** [comment]
Sad but true))

Could you please suggest how to properly define existing channel names with query params like in my example? We'd like to start using async api schema and tools but it seems to be a blocker

**Comment by Sergey-Terekhin** [comment]
Thanks! It works like a charm! We've been using NATS and it's possible to specify NATS queue name as we want:
```
asyncapi: 2.6.0
info:
  title: Test Service
  version: 1.0.0
channels:
  TestChannel:
    publish:
      bindings:
        nats:
          queue: TestChannel?Content-Type=application/json;charset=utf-8
      message:
        $ref: '#/components/messages/TestMessage'
components:
  messages:
    TestMessage:
      contentType: application/json
      description: test message model
```
