### ISSUE TITLE
JSON Schema preview is broken

### ISSUE THREAD

**Issue by kbolino** [asyncapi/vs-asyncapi-preview#194]
#### Describe the bug

If I try to preview a JSON schema file which has no connection to AsyncAPI, I get a white page with black text that says only:

> Error: The `asyncapi` field is missing.

#### How to Reproduce

Create a file `test.schema.json` with the following content:

```
{"$schema": "https://json-schema.org/draft-07/schema"}
```

Then click the "Preview AsyncAPI" button or Cmd+Shift+P (macOS) and select the option.

<img width="1203" alt="Screenshot 2023-09-27 at 18 22 38" src="https://github.com/asyncapi/vs-asyncapi-preview/assets/1722612/54ca1043-7558-4c17-a8b4-a2af3027f1ea">

This appears to be identical to [this issue from a similar plugin for IDEA](https://github.com/Pakisan/jasyncapi-idea-plugin/issues/35).

#### Expected behavior

Either the preview option should be unavailable (because it doesn't work on this file type) or, even better, I should see a nice overview of the schema (assuming it was not trivial, like the example I gave).

**Comment by ivangsa** [comment]
@kbolino thanks for reporting this issue.
We will fix this disabling AsyncAPI preview for non asyncapi files.

**Comment by Savio629** [comment]
So while debugging I found out that the isAsyncapi value could have caused the issue->

### For asyncapi.yaml files
![yamlisasyncapi](https://github.com/asyncapi/vs-asyncapi-preview/assets/91362589/d8a3b6e8-96bf-4522-9de8-e3761190c1c8)

### For asyncapi.json files
![jsonisasyncapi](https://github.com/asyncapi/vs-asyncapi-preview/assets/91362589/a7d2eb1e-f9ce-43cf-be0e-d98369663f00)

### For non asyncapi files
![wrongjsonisasyncapi](https://github.com/asyncapi/vs-asyncapi-preview/assets/91362589/f76959d6-5a26-4bef-9db6-ad66eaf92377)

### So by just adding the following condition AsyncAPI preview will be disable for non asyncapi files ->
![isasyncapi1](https://github.com/asyncapi/vs-asyncapi-preview/assets/91362589/91776a75-6fbb-4a76-9621-d2cc3934283b)

### Also for best practices would prefer using parenthesis here ->
![packagejsonerror](https://github.com/asyncapi/vs-asyncapi-preview/assets/91362589/cf4a0658-1875-4305-9b8c-248ce46f08d6)

**Comment by Savio629** [comment]
Should I open a pull request?
