### ISSUE TITLE
Components Schemas, Messages: Multiple level arrays not rendered completely.

### ISSUE THREAD

**Issue by AMulgrave** [asyncapi/vs-asyncapi-preview#203]
The following yaml snippet demonstrates object arrays not being rendered completely. Note, this type of construct will render correctly in OpenAPI.

asyncapi: 3.0.0
info:
  title: Show defect Service
  version: 1.0.0
  description: This message payload structures are not rendered completely
components:
  schemas:
    BlockItem:
      description: An item in a block. 
      type: object
      properties:
        Id:
          type: string
          format: guid
        Name:
          type: string
  messages:
    Add:
      description: Block item structure is only expanded for non array property
      payload:
        type: object
        properties:
          BlockItem:
            $ref: '#/components/schemas/BlockItem'
          BlockItems:
            type: array  
            Items:
              $ref: '#/components/schemas/BlockItem'

yaml formatting lost so file attached.
[asyncapi.yaml.txt](https://github.com/asyncapi/vs-asyncapi-preview/files/13883657/asyncapi.yaml.txt)
![Screenshot asyncapi defect](https://github.com/asyncapi/vs-asyncapi-preview/assets/152357274/e7897bd6-ffd3-43c6-a7f7-4f7165b549ee)

**Comment by ivangsa** [comment]
hi @AMulgrave 

it seems you have a typo in your asyncapi.yml: array items keyword should be lower case... and that renders ok

![image](https://github.com/asyncapi/vs-asyncapi-preview/assets/1246876/2bfe52c3-f76c-4436-b899-4577adde9423)

**Comment by AMulgrave** [comment]
My bad! Thankyou.
Of course, it would help if warnings and errors were displayed.
