### ISSUE TITLE
Outdated tutorial guides https://www.asyncapi.com/docs/tools/generator/generator-template

### ISSUE THREAD

**Issue by urizennnn** [asyncapi/vs-asyncapi-preview#216]
In the tutorial it has this snippet 
```
class TemperatureServiceClient:

  def __init__(self):
              self.client = mqtt.Client()
              self.client.connect(mqttBroker)
```
But this would throw an error because the python in this case now requires a callback api version specification. I researched further on how to fix and found out the the python client packages offer two version for api call back and any can be used in this case
```
CallbackAPIVersion.VERSION2
or
CallbackAPIVersion.VERSION1
```

so the fixed code should look something like this 
```
class TemperatureServiceClient:

  def __init__(self):
              self.client = mqtt.Client(CallbackAPIVersion.VERSION2)
              self.client.connect(mqttBroker)
 ```

**Comment by ivangsa** [comment]
Hi @urizennnn 

thanks for taking the time reporting this..

this is the repo for the vscode extension..

for the website/docs... can you create this issue again here?

![image](https://github.com/asyncapi/vs-asyncapi-preview/assets/1246876/7ebbcf3e-561d-45a6-a37b-13b894b8f65d)

**Comment by urizennnn** [comment]
> Hi @urizennnn
> 
> thanks for taking the time reporting this..
> 
> this is the repo for the vscode extension..
> 
> for the website/docs... can you create this issue again here?
> 
> ![image](https://private-user-images.githubusercontent.com/1246876/317292845-7ebbcf3e-561d-45a6-a37b-13b894b8f65d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NDc3MTksIm5iZiI6MTcxMTU0NzQxOSwicGF0aCI6Ii8xMjQ2ODc2LzMxNzI5Mjg0NS03ZWJiY2YzZS01NjFkLTQ1YTYtYTM3Yi0xM2I4OTRiOGY2NWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjdUMTM1MDE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTVlZjA4NTcxNWYyMGU0NmQ2OTc1OWZmNjRlOTA0OTcxMjMzNmMyMGM4NGE2YWI5NmNkZDU4NmVjZDI0ODA4OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nVBg16SPWTaEoyWPBunat6VWnsvwnX2ymE_cI_8dn_8)

oof sorry about that will do that now thanks
