### ISSUE TITLE
[BUG] Release to VS Code Marketplace fails

### ISSUE THREAD

**Issue by catosaurusrex2003** [asyncapi/vs-asyncapi-preview#246]
### Describe the bug.

https://github.com/asyncapi/vs-asyncapi-preview/actions/runs/11912516224/job/33196270192

### Expected behavior

with every release it should publish on vs code market place

### Screenshots

![image](https://github.com/user-attachments/assets/15394319-f328-4936-a8cf-2fc34ded8ff9)

### How to Reproduce

when a release happens in the repo

### 🥦 Browser

None

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by ivangsa** [comment]
@derberg access token to publish to VSCode marketplace has expired

**Comment by ivangsa** [comment]
token has been updated and released https://github.com/asyncapi/vs-asyncapi-preview/actions/runs/11912516224
thanks a lot @derberg
