### ISSUE TITLE
AsyncAPI do not support version of 2.1.0

### ISSUE THREAD

**Issue by CuteSmartTiger** [asyncapi/vs-asyncapi-preview#31]
first，i came across the same question like https://github.com/asyncapi/vs-asyncapi-preview/issues/4, i want write a list of list or a array of array, so  i try solve it in 2..1.0, write code like this
`recomm_station:
                type: array
                items:
                  type: array
                  items:
                    - type: number
                      description: ''
                    - type: number
                      description: ''
                    - type: number
                      description:''
 `
and i solve the problem , it can work ok  in https://playground.asyncapi.io/ ,but i comes error when i use it in vscode by AsyncAPI Preview ,the error as follow
`
Template render error: (/home/uisee/.vscode/extensions/ivangsa.asyncapi-preview-0.1.1/node_modules/@asyncapi/generator/node_modules/@asyncapi/html-template/template/index.html) Template render error: (/home/uisee/.vscode/extensions/ivangsa.asyncapi-preview-0.1.1/node_modules/@asyncapi/generator/node_modules/@asyncapi/html-template/partials/content.html) Template render error: (/home/uisee/.vscode/extensions/ivangsa.asyncapi-preview-0.1.1/node_modules/@asyncapi/generator/node_modules/@asyncapi/html-template/partials/operations.html) Error: Unable to call `the return value of (prop["items"])["properties"]`, which is undefined or falsey
`

**Comment by hkaur008** [comment]
Working on it !

**Comment by hkaur008** [comment]
Can some one guide me a little ?

**Comment by derberg** [comment]
@hkaur008 what do you need? for sure [these deps](https://github.com/asyncapi/vs-asyncapi-preview/blob/master/package.json#L125-L126) require update to latest

**Comment by hkaur008** [comment]
Like how to start and sync the updates

**Comment by derberg** [comment]
@ivangsa could you provide some guidance?

**Comment by ivangsa** [comment]
Hi,

I've tried to upgrade this dependencies with no luck:
```
    "@asyncapi/generator": "^1.8.0",
    "@asyncapi/html-template": "^0.23.7",
```
The main problem I was facing it's that AsyncAPIGenerator is unnable to find '@asyncapi/html-template'

This code is trying to find the package in `process.cwd()` folder which will be the cwd for vscode, not the current workspace folder, not where the extension is installed.
I've also tried to install html-template as global package but still was not found

![image](https://user-images.githubusercontent.com/1246876/134194014-f2288123-cad4-4d3d-9817-10fa57e4c18a.png)

Some pointers about this extension, which is a very simple implementation. There are mainly to files:
- src/extension.ts: for adding the "Asyncapi Preview" menu, starting PreviewServer and listening to changes on open files
- **src/PreviewServer.ts**: this is analog to the backend implementation of AsyncapiPlayground
  - Instantiates the AsyncAPI generator: `const asyncapiGenerator = new AsyncAPIGenerator('@asyncapi/html-template', tmpdir()....`
  - Starts an Express http server that will serve the index.html and a socketio server to send updated content from the extension to the webview/browser

I'm guessing this is the line you will need to fix for the generator to find the html-template. 

![image](https://user-images.githubusercontent.com/1246876/134195321-3a2919c5-125c-4dfd-9bd9-8e03f5a72264.png)

Once the generator can generate the html, upgrading to future versions should be easier as this is quite a big jump in versions...

Hope this helps you get going.

**Comment by ivangsa** [comment]
Regarding how to debug the extension:
- In vscode just press F5 to start a debuging instance
- Change setting `asyncapiPreview.previewInBrowser` in Preferences > Settings
- When you click "Asyncapi Preview" you can debug step by step both the server inside vscode and the client in the browser console

**Comment by hkaur008** [comment]
Okay thats making things little clear

**Comment by Ulrikop** [comment]
I would be happy if the plugin supports version 2.3.0

**Comment by ivangsa** [comment]
AsyncAPI vscode extension has been reworked using the latest [@asyncapi/asyncapi-react](https://github.com/asyncapi/asyncapi-react/tree/next) which is also de component used on  AsyncAPI Studio

It has also been relocated but it will autocatically upgrade itself if you already have it installed 
https://marketplace.visualstudio.com/items?itemName=asyncapi.asyncapi-preview 

I'm closing this issue as it should be fixed now.. but please recreate it if this issue still persist.

Thanks for your patience
