### ISSUE TITLE
Type array not supported

### ISSUE THREAD

**Issue by begolf-aci** [asyncapi/vs-asyncapi-preview#4]
Hi, I came across this bug while trying to use this extension. Here is a sample doc, if you drop it into the asynapi 2.0 playground works fine, but rendering from vcode using the plugin I get the following error:
Error: Unable to call `the return value of (prop["items"])["properties"]`, which is undefined or falsey
here is the full stack message:
Template render error: (c:\Users\ea\.vscode\extensions\ivangsa.asyncapi-preview-0.1.1\node_modules\@asyncapi\generator\node_modules\@asyncapi\html-template\template\index.html) 
Template render error: (c:\Users\ea\.vscode\extensions\ivangsa.asyncapi-preview-0.1.1\node_modules\@asyncapi\generator\node_modules\@asyncapi\html-template\partials\content.html) 
Template render error: (c:\Users\ea\.vscode\extensions\ivangsa.asyncapi-preview-0.1.1\node_modules\@asyncapi\generator\node_modules\@asyncapi\html-template\partials\operations.html) 
Error: Unable to call `the return value of (prop["items"])["properties"]`, which is undefined or falsey

Here is the doc, change the last line from  type: array  to type: string and it will render find with the extension.... 
thanks.

```yaml
asyncapi: 2.0.0
info:
  title: SAMPLE API
  version: 1.1.0
  description: SAMPLE ASYNCAPI spec
servers:
  production:
    url: my.rabbimq
    protocol: amqp
    description: My message broker.
channels:
  txn.authorized:
    publish:
      summary: Publish successful authorized transaction.
      operationId: RTPCE
      message:
        $ref: '#/components/messages/authorize-txn'
components:
  messages:
    authorize-txn:
      payload:
        type: object
        properties:
          message:
            type: object
            $ref: '#/components/schemas/message'
          _version:
            type: string
            description: 'the version of message schema'
            example: 'v7.3'
  schemas:
    message:
      type: object
      properties:
        code:
          type: array
```

**Comment by ivangsa** [comment]
ok, thanks @begolf-aci I will try to update asap the extension to the latest playground version
Thanks.

**Comment by derberg** [comment]
will be fixed with https://github.com/asyncapi/vs-asyncapi-preview/pull/47

**Comment by derberg** [comment]
it should be fixed now
