### ISSUE TITLE
Version 0.2 doesn't open relative reference

### ISSUE THREAD

**Issue by ThierryDrege** [asyncapi/vs-asyncapi-preview#96]
#### Describe the bug
Impossible to open an existing reference to an external file

#### How to Reproduce
components:
  messages:
    ProspectMessage:
      contentType: application/json
      description: This is a message notification when a sample is created 
      headers:
        $ref: "../Dictionary/flow.openapi.yaml#/components/schemas/MyHeader"
     payload:
        ..
=> **Preview AsyncAPI**
Error:
Error: Error downloading https://file+.vscode-resource.vscode-cdn.net/c%3A/projects/pm2/Dictionary/flow.openapi.yaml HTTP ERROR 401

#### Expected behavior
Work with asyncapi-preview v0.1.1

![image](https://user-images.githubusercontent.com/26802348/167846000-8eb239dc-4dbd-494c-aa06-6de33742986e.png)

**Comment by ivangsa** [comment]
Hi @ThierryDrege 

AsyncAPI vscode extension has been reworked using the latest [@asyncapi/asyncapi-react](https://github.com/asyncapi/asyncapi-react/tree/next) which is also de component used on  AsyncAPI Studio

It has also been relocated but it will autocatically upgrade itself if you already have it installed 
https://marketplace.visualstudio.com/items?itemName=asyncapi.asyncapi-preview 

I'm closing this issue as it should be fixed now.. but please recreate it if this issue still persist.

Thanks for your patience

**Comment by ThierryDrege** [comment]
Hi @ivangsa ,
With the new version, it is the same error
=> Preview AsyncAPI
Error:
Error: Error downloading https://file+.vscode-resource.vscode-cdn.net/c%3A/projects/pm2/Dictionary/flow.asyncapi.yaml HTTP ERROR 401

The base url is not the good one

the asyncapi contains:
headers:
  $ref: "../Dictionary/flow.asyncapi.yaml#/components/schemas/MyHeader"

**Comment by ivangsa** [comment]
Hi @ThierryDrege 

I got a fix for this.. it will work as long as referencing files are inside workspace folders

will release something shortly

Thanks a lot for reporting this.

**Comment by ThierryDrege** [comment]
Great, it's work perfectly
